### ISSUE TITLE
It would be awesome to support CORS in the images

### ISSUE THREAD

**Issue by dmcanosa** [thejsn/react-image-mosaic#1]
The project is great, but trying to use it i found that i need CORS support in order for it to work.
Would it be complicated to add it as an option for the image tag?
Thank you

**Comment by thejsn** [comment]
Hey, sorry for the late response. 
Do you mean setting the crossOrigin attribute on each image that's loaded? 
I could add a prop for that

**Comment by oraliahdz** [comment]
Hi, I'm struggling with the same issue. If I use external urls in Source, I get error "Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data", Is there something I might add to my code to solve it in the meantime?

**Comment by thejsn** [comment]
Ok, version 2.1.0 adds the prop `crossOrigin` which is then added to images that are loaded. Using `crossOrigin="anonymous"` should solve the issue.

**Comment by dmcanosa** [comment]
Thank you! Very helpful to have this feature
